# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
          # Runs a single command using the runners shell
          - name: Paso de Contruccion
            run: echo "Este es el paso de construccion"
  test:
      runs-on: ubuntu-latest
      needs: build
    
      steps:
        # Runs a single command using the runners shell
        - name: Paso de Testeo
          run: echo "Este es el paso de testeo"
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Runs a single command using the runners shell
      - name: Paso de deploy
        run: echo "Este es el paso de deploy"